modLoader="javafml"
loaderVersion="${loader_version}"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/TheIllusiveC4/CurioOfUndying/issues"
logoFile="curioofundying_icon.png"
logoBlur=false
[[mods]]
modId="curioofundying"
version="${version}"
displayName="Curio of Undying"
displayURL="https://github.com/TheIllusiveC4/CurioOfUndying"
authors="C4"
description='''
Adds curio support for the Totem of Undying so you don't have to be holding it.
'''
[[dependencies.curioofundying]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curioofundying]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.curioofundying]]
    modId="curios"
    mandatory=true
    versionRange="${curios_version_range}"
    ordering="NONE"
    side="BOTH"